# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  init:
    name: init
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v3

      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

  test:
    name: test
    needs: init
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fetch deps
        run: yarn

      - name: build
        run: yarn build

      - name: lint
        run: yarn run lint

      - name: test
        run: yarn run test:report

  build:
    name: build
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Save target (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: |
            !packages/*/node_modules
            !packages/*/src
            packages
            package.json


  test_push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore target
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: |
          sudo apt-get install moreutils
          yarn

      - name: build
        run: yarn build

      - name: Unit test only
        run: yarn test

      - name: Push coverage
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: coverage

  test_pr:
    if: github.event_name == 'pull_request'
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 14, 16 ]
    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore target
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          sudo apt-get install moreutils
          yarn

      - name: build
        run: yarn build

      - name: Unit test only
        if: matrix.node-version != '16' || matrix.os != 'ubuntu-20.04'
        run: yarn test
      - name: Full test with report
        if: matrix.node-version == '16' && matrix.os == 'ubuntu-20.04'
        run: yarn test:report

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test_push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Restore target
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Install deps
        run: |
          npm i -g npm@latest
          npm -v
          yarn -v
          yarn

      - name: Multi-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: 'qiwibot'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: 'opensource@qiwi.com'
          GIT_COMMITTER_EMAIL: 'opensource@qiwi.com'
          GIT_AUTHOR_NAME: '@qiwibot'
          GIT_COMMITTER_NAME: '@qiwibot'
        run: npx -p @qiwi/semrel-toolkit multi-semrel
